import React, { useState } from "react";
import { Link } from "react-router-dom";
import QRScanner from "../components/QRScanner";
import { recordAttendance } from "../services/db";
import { useAuth } from "../context/AuthProvider";

export default function ScanQR() {
  const { user, profile } = useAuth();
  const [last, setLast] = useState(null);
  const [status, setStatus] = useState({ type: "", message: "" });
  const [scanning, setScanning] = useState(true);

  const handleScan = async (decodedText) => {
    if (!decodedText || decodedText === last) return;
    setLast(decodedText);

    let sessionCode = decodedText;
    let sessionTitle = "3MTT Class";

    // Try parsing JSON payload if teacher generated structured data
    try {
      if (decodedText.startsWith("{")) {
        const parsed = JSON.parse(decodedText);
        sessionCode = parsed.session_code || decodedText;
        sessionTitle = parsed.title || "3MTT Class";
      }
    } catch (e) {
      // Raw string session code fallback
    }

    try {
      const studentIdentifier = user?.id || profile?.matric_number || user?.email;

      await recordAttendance({
        student_id: studentIdentifier,
        session_code: sessionCode,
        status: "Present",
      });

      setStatus({
        type: "success",
        message: `🎉 Attendance Verified! Marked PRESENT for "${sessionTitle}" (Code: ${sessionCode}).`,
      });
      setScanning(false);
    } catch (err) {
      console.error("Scan recording error:", err);
      setStatus({
        type: "error",
        message: err.message || `Scanned code ${sessionCode}, but attendance could not be saved.`,
      });
    }
  };

  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-emerald-700 text-white px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">3MTT QR Attendance</h1>
            <p className="text-emerald-100 text-sm">Student Attendance Scanner</p>
          </div>

          <Link
            to="/dashboard"
            className="bg-white text-emerald-800 px-4 py-2 rounded-lg font-medium hover:bg-emerald-50 transition text-sm"
          >
            Dashboard
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto p-6">
        <div className="bg-white p-6 rounded-2xl shadow-lg border text-center">
          <span className="bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
            Student Camera Scanner
          </span>

          <h2 className="text-2xl font-bold text-gray-800 mt-2">Scan Teacher's QR Code</h2>
          <p className="text-gray-500 text-sm mt-1 mb-6">
            Point your camera at the QR code generated by your teacher to record your attendance.
          </p>

          {/* Scanner Box */}
          {scanning ? (
            <div className="border-2 border-dashed border-emerald-300 rounded-xl p-4 bg-emerald-50/40">
              <QRScanner onScan={handleScan} />
            </div>
          ) : (
            <button
              onClick={() => {
                setScanning(true);
                setStatus({ type: "", message: "" });
              }}
              className="bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-xl font-bold text-sm transition shadow mb-4"
            >
              📷 Scan Another Session
            </button>
          )}

          {/* Feedback Status Alert */}
          {status.message && (
            <div
              className={`mt-5 p-4 rounded-xl text-left text-sm border font-medium ${
                status.type === "success"
                  ? "bg-emerald-50 text-emerald-800 border-emerald-300"
                  : "bg-amber-50 text-amber-800 border-amber-300"
              }`}
            >
              {status.message}
            </div>
          )}

          {last && (
            <div className="mt-4 text-xs font-mono text-gray-500 bg-gray-50 p-2.5 rounded-lg border">
              Scanned Payload: {last}
            </div>
          )}

          <div className="mt-6 flex justify-center gap-4 text-sm">
            <Link to="/attendance" className="text-emerald-700 font-semibold hover:underline">
              📋 My Attendance Log →
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
