import React, { useState } from "react";
import { Link } from "react-router-dom";
import QRScanner from "../components/QRScanner";
import { recordAttendance } from "../services/db";
import { useAuth } from "../context/AuthProvider";

export default function ScanQR() {
  const { user, profile } = useAuth();
  const [lastPayload, setLastPayload] = useState(null);
  const [status, setStatus] = useState({ type: "", message: "" });
  const [scanning, setScanning] = useState(true);

  const handleScan = async (decodedText) => {
    if (!decodedText || decodedText === lastPayload) return;
    setLastPayload(decodedText);

    let sessionCode = decodedText;
    let sessionTitle = "3MTT Track Session";

    // Parse JSON payload if teacher generated structured data
    try {
      if (decodedText.trim().startsWith("{")) {
        const parsed = JSON.parse(decodedText);
        sessionCode = parsed.session_code || parsed.code || decodedText;
        sessionTitle = parsed.title || parsed.course || "3MTT Track Session";
      }
    } catch (e) {
      // Fallback to raw string
    }

    try {
      const studentIdentifier = user?.id || profile?.matric_number || user?.email;

      await recordAttendance({
        student_id: studentIdentifier,
        session_code: sessionCode,
        status: "Present",
      });

      setStatus({
        type: "success",
        message: `🎉 Attendance Recorded! Marked PRESENT for "${sessionTitle}" (Code: ${sessionCode}).`,
      });
      setScanning(false);
    } catch (err) {
      console.error("Scan recording error:", err);
      setStatus({
        type: "error",
        message: err.message || `Scanned code ${sessionCode}, but attendance could not be saved.`,
      });
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      {/* Top Navbar */}
      <header className="bg-[#20203C] border-b border-slate-800 text-white px-4 sm:px-8 py-4 shadow-md sticky top-0 z-20">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="px-2.5 py-1.5 bg-[#008751] rounded-xl flex items-center justify-center font-extrabold text-xs shadow-md border border-emerald-400/20">
              3MTT
            </div>
            <div>
              <h1 className="text-lg font-bold text-white leading-none">QR Attendance Scanner</h1>
              <p className="text-slate-300 text-xs mt-0.5">3MTT Fellow Verification Portal</p>
            </div>
          </div>

          <Link
            to="/dashboard"
            className="bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 px-3.5 py-1.5 rounded-xl font-medium text-xs transition shadow-sm flex items-center gap-1.5"
          >
            ← Dashboard
          </Link>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-xl w-full mx-auto p-4 sm:p-6 flex flex-col justify-center">
        <div className="bg-white p-5 sm:p-8 rounded-3xl shadow-xl border border-slate-200/80 text-center">
          <div className="inline-flex items-center gap-1.5 bg-[#e6f1e6] border border-[#c9edcc] text-[#008751] px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider mb-3">
            <span className="w-2 h-2 rounded-full bg-[#008751] animate-pulse" />
            Live Camera Scanner
          </div>

          <h2 className="text-xl sm:text-2xl font-extrabold text-[#062324]">Scan Session QR Code</h2>
          <p className="text-slate-500 text-xs sm:text-sm mt-1 mb-6">
            Align the QR code generated by your 3MTT instructor within the frame to verify your attendance.
          </p>

          {/* Scanner or Reset View */}
          {scanning ? (
            <div className="my-2">
              <QRScanner onScan={handleScan} />
            </div>
          ) : (
            <div className="py-6 px-4 bg-[#e6f1e6]/40 rounded-2xl border border-[#c9edcc] my-2 flex flex-col items-center">
              <div className="w-14 h-14 bg-[#008751] text-white rounded-2xl flex items-center justify-center text-2xl mb-3 shadow-md border border-emerald-400/20">
                ✅
              </div>
              <h3 className="font-extrabold text-[#062324] text-base">Attendance Verified</h3>
              <p className="text-slate-500 text-xs mt-1 mb-5">Your attendance status has been saved to the server.</p>
              
              <button
                type="button"
                onClick={() => {
                  setScanning(true);
                  setStatus({ type: "", message: "" });
                  setLastPayload(null);
                }}
                className="bg-[#008751] hover:bg-[#26a65b] text-white px-6 py-2.5 rounded-xl font-bold text-xs sm:text-sm transition shadow-md flex items-center gap-2"
              >
                📷 Scan Another Code
              </button>
            </div>
          )}

          {/* Feedback Alert */}
          {status.message && (
            <div
              className={`mt-5 p-4 rounded-2xl text-left text-xs sm:text-sm border font-medium flex items-start gap-3 shadow-sm ${
                status.type === "success"
                  ? "bg-[#e6f1e6] text-[#008751] border-[#c9edcc]"
                  : "bg-rose-50 text-rose-800 border-rose-200"
              }`}
            >
              <span className="text-base">{status.type === "success" ? "🎉" : "⚠️"}</span>
              <div className="flex-1 font-semibold">{status.message}</div>
            </div>
          )}

          {lastPayload && (
            <div className="mt-4 text-[11px] font-mono text-slate-500 bg-slate-50 p-2.5 rounded-xl border border-slate-200 truncate">
              Payload: {lastPayload}
            </div>
          )}

          {/* Nav links */}
          <div className="mt-6 pt-5 border-t border-slate-100 flex items-center justify-between text-xs font-bold">
            <Link to="/attendance" className="text-[#008751] hover:underline flex items-center gap-1">
              📋 My Attendance Log →
            </Link>
            <Link to="/dashboard" className="text-slate-500 hover:text-slate-700 transition">
              Home
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
